title: NsJail
description: A light-weight process isolation tool, making use of Linux namespaces and seccomp-bpf
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
